// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xprrwkjotipgqhbchbju.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InhwcnJ3a2pvdGlwZ3FoYmNoYmp1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTEyOTQzNjYsImV4cCI6MjA2Njg3MDM2Nn0.FBf-7-p38nvCJFBUSLKpC16otZLGaT2JJkURhD5yAwY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});